### ISSUE TITLE
handle TODOS in script.js

### ISSUE THREAD

**Issue by mmmaaatttttt** [rithmschool/numbers_api#16]
Let's also format the code and do a general refactor: https://github.com/rithmschool/numbers_api/blob/master/public/js/script.js

**Comment by ngjamesng** [comment]
@mmmaaatttttt Thanks for assigning. I want to ask some questions in this ticket that may help now, or for future reference if I don't end up completing this. I think it'd be helpful for me or anyone in the future to understand the scope of the ticket. I apologize in advance if this is lengthy. 

Regarding a general refactor:
* I noticed the [/public/js/script.js](https://github.com/rithmschool/numbers_api/blob/master/public/js/script.js) and [/public/js/shared_utils.js](https://github.com/rithmschool/numbers_api/blob/master/public/js/shared_utils.js) files are using IIFEs and relies on the order of the script files in the HTML, making it a little hard understand where variables are coming from since they're implicitly being loaded through the order of the javascript files in the html. Does a general refactor mean to make use of `import` `export` and make variables from `var` to `let` or `const`? If so, there may be a tradeoff regarding the browser compatibility, more specifically for developers learning on internet explorer, which I hope isn't actually happening ☹️ . [import compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Browser_compatibility) - [export compatibility](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#Browser_compatibility)
I'm also not entirely sure if moving from IIFEs to import/export is possible or if it's even a common/preferred pattern, especially with an older codebase like this using jQuery.
* For a general refactor, I can think of converting things to let/const and use template literals, and indentation. Is there anything else that would make sense for a general refactor?

Regarding the todos:
* What does this mean exactly? I'd be glad to work on this but I'm not sure what is meant here. 
https://github.com/rithmschool/numbers_api/blob/f864c9b1e7815737e61fbce3b1c622c63b6eb4ab/public/js/script.js#L4-L5

* It sounds like this todo is to move lines 10 through 251 into `shared_utils.js`. Am I interpreting this line correctly? 
https://github.com/rithmschool/numbers_api/blob/f864c9b1e7815737e61fbce3b1c622c63b6eb4ab/public/js/script.js#L10-L14

* Upon a quick lookup, it looks like lionbars is jquery plugin that enables a scrolling window for the GUI's "try it out!" feature, useful if the fact is too lengthy. Lionbars is a dependency that hasn't been updated in 8-9 years. I do see 3 potential options... 1. try to work with the ancient dependency, 2.  find a less brittle alternative to implement a scrolling feature, or 3. accept that there can potentially be a UI/UX bug(which seems extremely rare that the facts get too long. I've yet to actually run into one.) 
I can imagine this todo being its own ticket if it ends up being complex. 
https://github.com/rithmschool/numbers_api/blob/f864c9b1e7815737e61fbce3b1c622c63b6eb4ab/public/js/script.js#L79-L82

**Comment by mmmaaatttttt** [comment]
Hey @ngjamesng -- thanks for digging into this. Some answers:

1. For the JS files in the public folder, you're right to be concerned about cross-browser support. For now, I think a light ES refactor of the type you propose (template literals, let / const, etc) is fine. If you're concerned about cross-browser support for a given JS feature, my go-to is [caniuse](https://caniuse.com/).
2. don't worry about import / export. Longer term we could think about using babel / webpack to build the public assets (we could even rewrite the public stuff in React), but i think that's probably beyond the scope of this issue.
3. re: the MVC comment, it's a bit vague to me as well, but suggests potentially moving towards a front-end framework to manage the state of the docs page. If those results in the comment need to be in sync, maybe for now just make a helper function that syncs them.
4. Re: the moving to shared_utils, i'd just move LL12-39 over for now, since those are the ones directly involving NUM_FROM_URL_REGEX. maybe having those accessible to the backend as well will simplify the backend? not sure.
5. lionbars sounds weird, i don't see a reason to try to match the UI of an OSX version that's basically a decade old. is it for the scrollbars that appear e.g. in this scenario?

<img width="297" alt="Screen Shot 2020-07-14 at 1 48 24 PM" src="https://user-images.githubusercontent.com/3916770/87475552-db893980-c5d9-11ea-89d2-ab2c0a361e1d.png">

i'd try removing and see what the scrollbars look like.

**Comment by ngjamesng** [comment]
Thanks Matt. I've knocked out a couple of the TODOs in my fork, but I'm a bit stumped on the following:

* I spent quite a while on this, and I'm afraid to admit I'm stuck, and I know you mentioned to look at the `Makefile`. I still have no clue how to properly run the Ruby Compass CSS compiler. I've been unable to tackle the TODO that relates to styling/lionbars, and I'm unable to get styling or scrollbars to appear. I'm quite unfamiliar with what to do here :(. 
```
master numbers_api $ make
compass clean public/
LoadError on line ["54"] of /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- compass_twitter_bootstrap
Run with --trace to see the full backtrace
make: *** [compass] Error 1
master numbers_api $ 
```

* This seems more like a comment on the functionality than anything else, but I'm assuming it means to "find a more robust solution" and I can't think of how I'd do it differently/not entirely sure what problem this is solving. `addThis` seems to be related to some of the analytics functionality, which seems to be commented out. 
https://github.com/rithmschool/numbers_api/blob/f864c9b1e7815737e61fbce3b1c622c63b6eb4ab/public/js/script.js#L291-L296

* You mentioned earlier to have a helper function/ eventually move to a framework that syncs the result. (More to follow)
https://github.com/rithmschool/numbers_api/blob/f864c9b1e7815737e61fbce3b1c622c63b6eb4ab/public/js/script.js#L4-L6
I may have glossed over this during my initial look-over of the code. Does the following helper function seem to do what you suggested? If so I can just remove the TODO. Would you agree?
https://github.com/rithmschool/numbers_api/blob/f864c9b1e7815737e61fbce3b1c622c63b6eb4ab/public/js/script.js#L144-L149

Other than that, almost ready for a PR!

**Comment by mmmaaatttttt** [comment]
1. I updated this issue: https://github.com/rithmschool/numbers_api/issues/11 to reference the todo related to `addThis`, i think it's fine to ignore for now.
2. maybe? i'm not sure. i don't know if `update_all` pertains to "search text" or "selected example", since i don't totally understand what that comment is referring to.
